-- Seed data for main_objects / sub_objects / documents, generated from Annexure A.
-- Run after 0001_init.sql.

insert into main_objects (id, level, name, domain_specific, sort_order) values
  (1, 'Basic', 'Introduction to EWM', false, 1),
  (2, 'Basic', 'ERP–EWM Integration', false, 2),
  (3, 'Basic', 'Org Elements & Master Data', false, 3),
  (4, 'Basic', 'Warehouse Process Type (WPT)', false, 4),
  (5, 'Basic', 'Putaway Process', false, 5),
  (6, 'Basic', 'Storage Control', false, 6),
  (7, 'Basic', 'Handling Unit Management', false, 7),
  (8, 'Basic', 'Inbound Delivery / Goods Receipt', true, 8),
  (9, 'Basic', 'Outbound Delivery / Goods Issue', true, 9),
  (10, 'Basic', 'Stock Transfer + Replenishment', false, 10),
  (11, 'Basic', 'Quality Management Integration', true, 11),
  (12, 'Basic', 'Physical Inventory', false, 12),
  (13, 'Basic', 'Post Processing Framework (PPF)', false, 13),
  (14, 'Basic', 'RF Framework + Resource Management', false, 14),
  (15, 'Advance', 'Yard Management', false, 15),
  (16, 'Advance', 'Packing Work Center', false, 16),
  (17, 'Advance', 'Cross Docking', false, 17),
  (18, 'Advance', 'Batch Management', true, 18),
  (19, 'Advance', 'Exception Handling', false, 19),
  (20, 'Advance', 'Slotting & Rearrangement', false, 20),
  (21, 'Advance', 'Wave Management', false, 21),
  (22, 'Advance', 'Serialization Profile', false, 22),
  (23, 'Advance', 'Advanced Production Integration (PP-EWM)', true, 23),
  (24, 'Advance', 'Production Integration (PMR)', true, 24),
  (25, 'Advance', 'Deconsolidation', false, 25),
  (26, 'Advance', 'Value Added Services (VAS)', false, 26),
  (27, 'Super Advance', 'Material Flow System (MFS)', false, 27),
  (28, 'Super Advance', 'Advanced Shipping & Receiving (ASR)', false, 28),
  (29, 'Super Advance', 'Dock Appointment Scheduling (DAS)', false, 29),
  (30, 'Super Advance', 'Cartonization Planning (CAP)', false, 30),
  (31, 'Super Advance', 'EWM ABAP Fundamentals', false, 31),
  (32, 'Super Advance', 'Labor Management (LM)', false, 32),
  (33, 'Super Advance', 'RF Framework (ITS → MOBGUI)', false, 33),
  (34, 'Super Advance', 'MES Integration', false, 34),
  (35, 'Super Advance', 'AGV / 3PL Integration via IDoc', true, 35);

insert into sub_objects (id, main_object_id, name, sort_order) values
  ('1.1', 1, 'Overview & deployment options (Embedded vs Decentralized)', 1),
  ('2.1', 2, 'Delivery document integration', 1),
  ('2.2', 2, 'Data distribution model/queues', 2),
  ('2.3', 2, 'Availability group & party entitled to dispose', 3),
  ('3.1', 3, 'Storage type/section/bin setup', 1),
  ('3.2', 3, 'Activity area & work center', 2),
  ('3.3', 3, 'ERP org-element mapping', 3),
  ('3.4', 3, 'Product/UOM master in EWM', 4),
  ('4.1', 4, 'WPT creation/modification', 1),
  ('4.2', 4, 'WPT determination', 2),
  ('5.1', 5, 'Simple putaway w/o HU', 1),
  ('5.2', 5, 'Putaway with HU + strategy', 2),
  ('5.3', 5, '2-step putaway', 3),
  ('5.4', 5, 'Putaway rules/strategies config', 4),
  ('6.1', 6, 'Process-oriented Storage Control (POSC)', 1),
  ('6.2', 6, 'Layout-oriented Storage Control (LOSC)', 2),
  ('7.1', 7, 'HU with packing specification', 1),
  ('7.2', 7, 'HU without packing specification', 2),
  ('7.3', 7, 'Manual vs Automatic HU creation', 3),
  ('8.1', 8, 'Simple inbound w/wo HU', 1),
  ('8.2', 8, 'POSC+LOSC inbound with HU', 2),
  ('8.3', 8, 'GR from Production', 3),
  ('8.4', 8, 'GR from STO', 4),
  ('8.5', 8, 'GR from Customer Returns', 5),
  ('9.1', 9, 'Simple GI w/wo HU', 1),
  ('9.2', 9, 'POSC Pick+Stage+Load', 2),
  ('9.3', 9, 'GI to Production (staging)', 3),
  ('9.4', 9, 'GI for STO', 4),
  ('9.5', 9, 'Wave-based GI release', 5),
  ('10.1', 10, 'Ad-hoc stock transfer/posting change', 1),
  ('10.2', 10, 'Planned replenishment', 2),
  ('10.3', 10, 'Automatic min-max replenishment', 3),
  ('11.1', 11, '100% inspection', 1),
  ('11.2', 11, 'Skip lot', 2),
  ('12.1', 12, 'Annual PI', 1),
  ('12.2', 12, 'Ad-hoc PI', 2),
  ('12.3', 12, 'Difference Analyzer', 3),
  ('12.4', 12, 'Low stock/zero check', 4),
  ('13.1', 13, 'PPF in delivery processing', 1),
  ('13.2', 13, 'PPF for HU creation', 2),
  ('14.1', 14, 'RF putaway/picking transactions', 1),
  ('14.2', 14, 'RF menu/framework config', 2),
  ('14.3', 14, 'Resource/queue management', 3),
  ('15.1', 15, 'Check-in/checkout', 1),
  ('15.2', 15, 'Spot/parking assignment', 2),
  ('15.3', 15, 'End-to-end configuration', 3),
  ('16.1', 16, 'Packing with POSC', 1),
  ('16.2', 16, 'Work center determination', 2),
  ('17.1', 17, 'Opportunistic cross docking', 1),
  ('17.2', 17, 'Planned/transportation-driven cross docking', 2),
  ('18.1', 18, 'Batch creation/classification', 1),
  ('18.2', 18, 'Batch determination in outbound', 2),
  ('18.3', 18, 'Shelf-life/expiry handling', 3),
  ('19.1', 19, 'Standard exception code configuration', 1),
  ('19.2', 19, 'Custom exception code (e.g. Pick Denial BIDP/BIDF/BPRP/BFRP)', 2),
  ('20.1', 20, 'Slotting run', 1),
  ('20.2', 20, 'Rearrangement execution', 2),
  ('21.1', 21, 'Wave template/type configuration', 1),
  ('21.2', 21, 'Manual wave', 2),
  ('21.3', 21, 'Automatic wave generation for WPT', 3),
  ('22.1', 22, 'Serial number in inbound', 1),
  ('22.2', 22, 'Serial number in outbound', 2),
  ('23.1', 23, 'Staging & consumption', 1),
  ('23.2', 23, 'Receipt from production', 2),
  ('23.3', 23, 'Advanced production integration vs outbound production', 3),
  ('24.1', 24, 'PMR-based staging concept (dynamic pull-list determination)', 1),
  ('24.2', 24, 'PMR control cycle & configuration', 2),
  ('24.3', 24, 'PMR replenishment/pull execution', 3),
  ('25.1', 25, 'Deconsolidation process overview (breaking HUs post-GR)', 1),
  ('25.2', 25, 'Deconsolidation with cross-docking', 2),
  ('25.3', 25, 'Deconsolidation configuration', 3),
  ('26.1', 26, 'VAS process overview (kitting/labeling/repacking)', 1),
  ('26.2', 26, 'VAS work center processing', 2),
  ('26.3', 26, 'VAS configuration & pricing/costing hooks', 3),
  ('27.1', 27, 'Architecture/structural elements', 1),
  ('27.2', 27, 'MFS inbound E2E flow', 2),
  ('27.3', 27, 'Setup w/o emulator', 3),
  ('27.4', 27, 'ABAP layer', 4),
  ('27.5', 27, 'Exception handling + automated warehouse types', 5),
  ('28.1', 28, 'ASR vs LDAP/Direct integration', 1),
  ('28.2', 28, 'Technical architecture & configuration', 2),
  ('28.3', 28, 'Inbound process flow', 3),
  ('28.4', 28, 'Outbound flow + customer return scenario', 4),
  ('29.1', 29, 'EWM-initiated planning', 1),
  ('29.2', 29, 'TM-initiated planning', 2),
  ('30.1', 30, 'Basic cartonization (outbound/wave)', 1),
  ('30.2', 30, 'Advanced cartonization (WOCR)', 2),
  ('30.3', 30, 'Master data & BAdI config', 3),
  ('31.1', 31, 'BAdIs / FMs / enhancement spots', 1),
  ('32.1', 32, 'Workforce planning', 1),
  ('32.2', 32, 'Task management/execution', 2),
  ('32.3', 32, 'Productivity & performance tracking', 3),
  ('33.1', 33, 'MOBGUI activation & testing', 1),
  ('33.2', 33, 'RF personalization/menu design', 2),
  ('34.1', 34, 'Synchronous production integration', 1),
  ('35.1', 35, 'WMTORD (outbound task IDoc)', 1),
  ('35.2', 35, 'WMTOCO (task confirmation IDoc)', 2),
  ('35.3', 35, 'Cancellation IDoc', 3),
  ('35.4', 35, 'Confirmation IDoc', 4),
  ('35.5', 35, 'Exception IDoc', 5),
  ('35.6', 35, 'GR IDoc', 6),
  ('35.7', 35, 'Synchronous GR IDoc', 7);

-- One document row per sub-object per domain variant, all starting as 'draft'.
insert into documents (sub_object_id, domain, status) values
  ('1.1', 'Standard', 'draft'),
  ('2.1', 'Standard', 'draft'),
  ('2.2', 'Standard', 'draft'),
  ('2.3', 'Standard', 'draft'),
  ('3.1', 'Standard', 'draft'),
  ('3.2', 'Standard', 'draft'),
  ('3.3', 'Standard', 'draft'),
  ('3.4', 'Standard', 'draft'),
  ('4.1', 'Standard', 'draft'),
  ('4.2', 'Standard', 'draft'),
  ('5.1', 'Standard', 'draft'),
  ('5.2', 'Standard', 'draft'),
  ('5.3', 'Standard', 'draft'),
  ('5.4', 'Standard', 'draft'),
  ('6.1', 'Standard', 'draft'),
  ('6.2', 'Standard', 'draft'),
  ('7.1', 'Standard', 'draft'),
  ('7.2', 'Standard', 'draft'),
  ('7.3', 'Standard', 'draft'),
  ('8.1', 'Manufacturing', 'draft'),
  ('8.1', 'Pharma', 'draft'),
  ('8.2', 'Manufacturing', 'draft'),
  ('8.2', 'Pharma', 'draft'),
  ('8.3', 'Manufacturing', 'draft'),
  ('8.3', 'Pharma', 'draft'),
  ('8.4', 'Manufacturing', 'draft'),
  ('8.4', 'Pharma', 'draft'),
  ('8.5', 'Manufacturing', 'draft'),
  ('8.5', 'Pharma', 'draft'),
  ('9.1', 'Manufacturing', 'draft'),
  ('9.1', 'Pharma', 'draft'),
  ('9.2', 'Manufacturing', 'draft'),
  ('9.2', 'Pharma', 'draft'),
  ('9.3', 'Manufacturing', 'draft'),
  ('9.3', 'Pharma', 'draft'),
  ('9.4', 'Manufacturing', 'draft'),
  ('9.4', 'Pharma', 'draft'),
  ('9.5', 'Manufacturing', 'draft'),
  ('9.5', 'Pharma', 'draft'),
  ('10.1', 'Standard', 'draft'),
  ('10.2', 'Standard', 'draft'),
  ('10.3', 'Standard', 'draft'),
  ('11.1', 'Manufacturing', 'draft'),
  ('11.1', 'Pharma', 'draft'),
  ('11.2', 'Manufacturing', 'draft'),
  ('11.2', 'Pharma', 'draft'),
  ('12.1', 'Standard', 'draft'),
  ('12.2', 'Standard', 'draft'),
  ('12.3', 'Standard', 'draft'),
  ('12.4', 'Standard', 'draft'),
  ('13.1', 'Standard', 'draft'),
  ('13.2', 'Standard', 'draft'),
  ('14.1', 'Standard', 'draft'),
  ('14.2', 'Standard', 'draft'),
  ('14.3', 'Standard', 'draft'),
  ('15.1', 'Standard', 'draft'),
  ('15.2', 'Standard', 'draft'),
  ('15.3', 'Standard', 'draft'),
  ('16.1', 'Standard', 'draft'),
  ('16.2', 'Standard', 'draft'),
  ('17.1', 'Standard', 'draft'),
  ('17.2', 'Standard', 'draft'),
  ('18.1', 'Manufacturing', 'draft'),
  ('18.1', 'Pharma', 'draft'),
  ('18.2', 'Manufacturing', 'draft'),
  ('18.2', 'Pharma', 'draft'),
  ('18.3', 'Manufacturing', 'draft'),
  ('18.3', 'Pharma', 'draft'),
  ('19.1', 'Standard', 'draft'),
  ('19.2', 'Standard', 'draft'),
  ('20.1', 'Standard', 'draft'),
  ('20.2', 'Standard', 'draft'),
  ('21.1', 'Standard', 'draft'),
  ('21.2', 'Standard', 'draft'),
  ('21.3', 'Standard', 'draft'),
  ('22.1', 'Standard', 'draft'),
  ('22.2', 'Standard', 'draft'),
  ('23.1', 'Manufacturing', 'draft'),
  ('23.1', 'Pharma', 'draft'),
  ('23.2', 'Manufacturing', 'draft'),
  ('23.2', 'Pharma', 'draft'),
  ('23.3', 'Manufacturing', 'draft'),
  ('23.3', 'Pharma', 'draft'),
  ('24.1', 'Manufacturing', 'draft'),
  ('24.1', 'Pharma', 'draft'),
  ('24.2', 'Manufacturing', 'draft'),
  ('24.2', 'Pharma', 'draft'),
  ('24.3', 'Manufacturing', 'draft'),
  ('24.3', 'Pharma', 'draft'),
  ('25.1', 'Standard', 'draft'),
  ('25.2', 'Standard', 'draft'),
  ('25.3', 'Standard', 'draft'),
  ('26.1', 'Standard', 'draft'),
  ('26.2', 'Standard', 'draft'),
  ('26.3', 'Standard', 'draft'),
  ('27.1', 'Standard', 'draft'),
  ('27.2', 'Standard', 'draft'),
  ('27.3', 'Standard', 'draft'),
  ('27.4', 'Standard', 'draft'),
  ('27.5', 'Standard', 'draft'),
  ('28.1', 'Standard', 'draft'),
  ('28.2', 'Standard', 'draft'),
  ('28.3', 'Standard', 'draft'),
  ('28.4', 'Standard', 'draft'),
  ('29.1', 'Standard', 'draft'),
  ('29.2', 'Standard', 'draft'),
  ('30.1', 'Standard', 'draft'),
  ('30.2', 'Standard', 'draft'),
  ('30.3', 'Standard', 'draft'),
  ('31.1', 'Standard', 'draft'),
  ('32.1', 'Standard', 'draft'),
  ('32.2', 'Standard', 'draft'),
  ('32.3', 'Standard', 'draft'),
  ('33.1', 'Standard', 'draft'),
  ('33.2', 'Standard', 'draft'),
  ('34.1', 'Standard', 'draft'),
  ('35.1', 'Manufacturing', 'draft'),
  ('35.1', 'Pharma', 'draft'),
  ('35.2', 'Manufacturing', 'draft'),
  ('35.2', 'Pharma', 'draft'),
  ('35.3', 'Manufacturing', 'draft'),
  ('35.3', 'Pharma', 'draft'),
  ('35.4', 'Manufacturing', 'draft'),
  ('35.4', 'Pharma', 'draft'),
  ('35.5', 'Manufacturing', 'draft'),
  ('35.5', 'Pharma', 'draft'),
  ('35.6', 'Manufacturing', 'draft'),
  ('35.6', 'Pharma', 'draft'),
  ('35.7', 'Manufacturing', 'draft'),
  ('35.7', 'Pharma', 'draft');

